version: '3'

# Each service runs in a separate container
services:
    # the name of the service
    postgres-db:
        container_name: match-db
        image: postgres:latest
        restart: always
        environment:
            DATABASE_HOST: 127.0.0.1
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: match
            POSTGRES_PORT: 5432
            POSTGRES_DB: match
            PGDATA: /var/lib/postgresql/data
        ports:
            - "5432:5432"


        
volumes:
  pgdatasource: